version: '{build}'

branches:
  only:
  - master
  - develop

image:
- Ubuntu2004
- Visual Studio 2022
- Visual Studio 2019

matrix:
  fast_finish: false

init:
- cmd: |-
    echo %APPVEYOR_BUILD_WORKER_IMAGE%
    if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2019" ( set generator="Visual Studio 16 2019" )
    if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2022" ( set generator="Visual Studio 17 2022" )
    echo %generator%
- sh: |-
    pushd .
    cd $HOME
    python --version
    git clone https://github.com/emscripten-core/emsdk.git
    cd emsdk
    ./emsdk install 3.1.4
    ./emsdk activate 3.1.4
    source ./emsdk_env.sh
    popd

install:
- sh: |-
    sudo apt-get update
    sudo apt-get install -y gcovr

before_build:
- cmd: |-
    mkdir build
    cd build
    cmake --version
    cmake -G %generator% -A x64 ..
- sh: |-
    cmake --version

    echo && echo "------- GCC PROJECT GENERATION -------"
    mkdir build-gcc
    cd build-gcc
    gcc-7 --version
    cmake -G Ninja \
     -DCMAKE_BUILD_TYPE=Debug \
     -DREACTIVE_CPP_COVERAGE=ON \
     -DCMAKE_CXX_COMPILER=g++-7 \
     ..
    cd ..

    echo && echo "------- CLANG PROJECT GENERATION -------"
    mkdir build-clang
    cd build-clang
    clang++-9 --version
    cmake -DCMAKE_CXX_COMPILER=clang++-9 -G Ninja -DCMAKE_BUILD_TYPE=Debug ..
    cd ..

    echo && echo "------- EMSCRIPTEN PROJECT GENERATION -------"
    mkdir build-emscripten
    cd build-emscripten
    $EMSDK/upstream/emscripten/emcc -v
    cmake \
     -DCMAKE_TOOLCHAIN_FILE="$EMSDK/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake" \
     -G Ninja -DCMAKE_BUILD_TYPE=Debug ..
     cd ..

    echo && echo "------- COVERAGE PROJECT GENERATION -------"
    mkdir build-coverage
    cd build-coverage
    gcc-9 --version
    cmake -G Ninja \
     -DCMAKE_BUILD_TYPE=Debug \
     -DREACTIVE_CPP_COVERAGE=ON \
     -DCMAKE_CXX_COMPILER=g++-9 \
     ..
    cd ..


build_script:
- cmd: cmake --build . --config Debug -- /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
- sh: |-
    echo && echo "------- GCC BUILD -------"
    cmake --build build-gcc
    echo && echo "------- CLANG BUILD -------"
    cmake --build build-clang
    echo && echo "------- EMSCRIPTEN BUILD -------"
    cmake --build build-emscripten
    echo && echo "------- COVERAGE BUILD -------"
    cmake --build build-coverage --target circle-reactive-coverage-xml

test_script:
- cmd: |-
    cd test\Debug\
    circle-reactive-test.exe
- sh: |-
    echo && echo "------- GCC BUILD TEST -------" && ./build-gcc/test/circle-reactive-test
    echo && echo "------- CLANG BUILD TEST -------" && ./build-clang/test/circle-reactive-test
    echo && echo "------- EMSCRIPTEN BUILD TEST -------" && node ./build-emscripten/test/circle-reactive-test

on_success:
- sh: |-
    cd build-coverage/test
    curl -Os https://uploader.codecov.io/latest/linux/codecov
    chmod +x codecov
    ./codecov -f circle-reactive-test-coverage.xml
